#ifdef MODULE_SCRIPT_ENABLED

#ifdef MODULE_PHYSICS_ENABLED

// Autogenerated by gameplay-luagen
#ifndef LUA_PHYSICSCONTROLLERLISTENER_H_
#define LUA_PHYSICSCONTROLLERLISTENER_H_

namespace gameplay
{

// Lua bindings for PhysicsController::Listener.
int lua_PhysicsControllerListener_statusEvent(lua_State* state);

void luaRegister_PhysicsControllerListener();

}

#endif

#endif // #ifdef MODULE_PHYSICS_ENABLED

#endif // #ifdef MODULE_SCRIPT_ENABLED