// Autogenerated by gameplay-luagen
#ifndef LUA_ANIMATIONCONTROLLER_H_
#define LUA_ANIMATIONCONTROLLER_H_

#ifdef MODULE_SCRIPT_ENABLED

namespace gameplay
{

// Lua bindings for AnimationController.
int lua_AnimationController_stopAllAnimations(lua_State* state);

void luaRegister_AnimationController();

}

#endif // #ifdef MODULE_SCRIPT_ENABLED

#endif
