// Autogenerated by gameplay-luagen
#ifndef LUA_MOUSE_H_
#define LUA_MOUSE_H_

#ifdef MODULE_SCRIPT_ENABLED

namespace gameplay
{

// Lua bindings for Mouse.
int lua_Mouse__gc(lua_State* state);

void luaRegister_Mouse();

}

#endif // #ifdef MODULE_SCRIPT_ENABLED

#endif
