// Autogenerated by gameplay-luagen
#ifndef LUA_TOUCH_H_
#define LUA_TOUCH_H_

#ifdef MODULE_SCRIPT_ENABLED

namespace gameplay
{

// Lua bindings for Touch.
int lua_Touch__gc(lua_State* state);
int lua_Touch_static_MAX_TOUCH_POINTS(lua_State* state);

void luaRegister_Touch();

}

#endif // #ifdef MODULE_SCRIPT_ENABLED

#endif
