// Autogenerated by gameplay-luagen
#ifndef LUA_AUDIOCONTROLLER_H_
#define LUA_AUDIOCONTROLLER_H_

#ifdef MODULE_SCRIPT_ENABLED

namespace gameplay
{

// Lua bindings for AudioController.
int lua_AudioController__gc(lua_State* state);

void luaRegister_AudioController();

}

#endif // #ifdef MODULE_SCRIPT_ENABLED

#endif
