// Autogenerated by gameplay-luagen
#ifndef LUA_LOGGER_H_
#define LUA_LOGGER_H_

#ifdef MODULE_SCRIPT_ENABLED

namespace gameplay
{

// Lua bindings for Logger.
int lua_Logger_static_isEnabled(lua_State* state);
int lua_Logger_static_log(lua_State* state);
int lua_Logger_static_set(lua_State* state);
int lua_Logger_static_setEnabled(lua_State* state);

void luaRegister_Logger();

}

#endif // #ifdef MODULE_SCRIPT_ENABLED

#endif
