// Autogenerated by gameplay-luagen
#ifndef LUA_ANIMATIONCLIPLISTENER_H_
#define LUA_ANIMATIONCLIPLISTENER_H_

#ifdef MODULE_SCRIPT_ENABLED

namespace gameplay
{

// Lua bindings for AnimationClip::Listener.
int lua_AnimationClipListener__gc(lua_State* state);
int lua_AnimationClipListener_animationEvent(lua_State* state);

void luaRegister_AnimationClipListener();

}

#endif // #ifdef MODULE_SCRIPT_ENABLED

#endif
